package com.woniu.vueserver.entity;

import java.io.Serializable;
import java.util.List;

public class Province implements Serializable {
    private List citys;

    public List getCitys() {
        return citys;
    }

    public void setCitys(List citys) {
        this.citys = citys;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pid
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pid
     *
     * @return the value of province.pid
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pid
     *
     * @param pid the value for province.pid
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbggenerated Fri May 29 16:07:35 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}