server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prj26?characterEncoding=UTF-8
    username: root
    password: ilovelaohan
  mvc:
    view:
      prefix: /
      suffix: .jsp
