package com.woniu.cls26prj.entity;

public class RoletreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.rid
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.id
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.rid
     *
     * @return the value of roletree.rid
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.rid
     *
     * @param rid the value for roletree.rid
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.id
     *
     * @return the value of roletree.id
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.id
     *
     * @param id the value for roletree.id
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }
}