package com.woniu.cls26prj.mapper;

import com.woniu.cls26prj.entity.UserinforoleExample;
import com.woniu.cls26prj.entity.UserinforoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinforoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int countByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int deleteByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int deleteByPrimaryKey(UserinforoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int insert(UserinforoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int insertSelective(UserinforoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    List<UserinforoleKey> selectByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserinforoleKey record, @Param("example") UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Wed May 27 10:18:18 CST 2020
     */
    int updateByExample(@Param("record") UserinforoleKey record, @Param("example") UserinforoleExample example);
}